name: nasbridge
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-334.4.beta

# Add regular dependencies here.
dependencies:
  runtime_type: ^1.1.0 
  meta: ^1.16.0
  logging: ^1.3.0
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
